#!/usr/bin/env bash
# CONFIGigure server with: HAproxy version 1.5 or greater
apt-get update -y
apt-get install -y haproxy

CONFIG="\
frontend main
	bind *:80
	mode http
	default_backend web-server
backend web-server
	balance roundrobin
	server 1861-web-01 34.74.125.88:80 check
	server 1861-web-02 35.243.133.178:80 check
"

sudo echo "$CONFIG" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart
